### PR TITLE
Use markdown for V4 stories and series, but continue to return html for description

### PR DESCRIPTION
**Pull request by kookster**
- [x] Add description_md attribute with md value of description
- [x] Render v4 descriptions from md -> html for description field
- [x] Render v3 descriptions from html ->  for description_md field
- [x] Allow updating the desc also as description_md

### CODE REVIEW

**Comment by kookster** [comment]
@sandikbarr added you on here as well so you can see what madness is happening with cms and markdown

**Comment by kookster** [comment]
@sandikbarr @cavis this is the one that breaks how markdown is retrieved from the cms api - are we ready to do this and break publish?

**Comment by sandikbarr** [comment]
@kookster @cavis I'm ready. I can open a PR for switching this field this afternoon.

**Comment by sandikbarr** [comment]
@cavis @kookster Opened a Publish PR for this change https://github.com/PRX/publish.prx.org/pull/158. Not sure if I should have added another field for description_md. I just pointed it to the existing description member variable since we are not using the html formatted description anywhere. I opted for making the least amount of changes, but I can certainly add description_md as an additional variable and keep the html in the description field on the story and series model instead.

**Pull request merged**
