### PR TITLE
Camelize resource attribute names in json requests

### PR DESCRIPTION
**Pull request by kookster**
- [x] monkey patch hyperresource to use outgoing_body_filter

### CODE REVIEW

**Comment by kookster** [comment]
That test is still failing sometimes, let me see if I can fix it.

**Comment by kookster** [comment]
@cavis I believe hound is as happy as it will be, since I have code copied from the `hyperresource` gem I don't want to mess with. It will get better if `hyperresource` gets fixed...

**Comment by kookster** [comment]
@cavis I think that test will keep passing, but I've been wrong before!

**Comment by cavis** [comment]
Woooo!  First CMS PR to ever pass all the checks!

**Pull request merged**
